name: dry-struct
codacy_id: 961f5c776f1d49218b2cede3745e059c
gemspec:
  authors: ["Piotr Solnica"]
  email: ["piotr.solnica@gmail.com"]
  summary: "Typed structs and value objects"
  runtime_dependencies:
    - [zeitwerk, "~> 2.6"]
    - [dry-core, "~> 1.1"]
    - [dry-types, "~> 1.8", ">= 1.8.2"]
    - [ice_nine, "~> 0.11"]
